TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.GoogleMaps': TRUE
    nodeTypes:
      groups:
        special:
          position: 50
          label: 'Special Content'

Dotpulse:
  GoogleMaps:
    includeGoogleAPI: TRUE
    includeFunction: TRUE
    includeCSS: FALSE
    googleAPI: '//maps.google.com/maps/api/js?callback=initMaps'
